### ISSUE TITLE
Fix the footer at the bottom

### ISSUE THREAD

**Issue by aakankshaduggal** [operate-first/website-ng#20]
A suggestion for the new website design.

I feel if we fix the footer to the bottom of the page, it'd be great. 
Right now it looks something like this :

![image](https://user-images.githubusercontent.com/26301643/167894985-7f91ddc3-20f5-4712-bf37-205dea7b723d.png)

Fixing the footer at the bottom will make the pages look more organized and neat.

**Comment by bryanmontalvan** [comment]
@aakankshaduggal We can keep the footer fixed to the bottom, but the only issue is that it can overlay over other content. The reason why the footer is so high is because we have not populated the page with content :(
